### ISSUE TITLE
Any news on the platform.io support?

### ISSUE THREAD

**Issue by synth3** [HelTecAutomation/ASR650x-Arduino#90] opened 2020-05-04 22:05 UTC
Hi there, are there any news regarding the platform.io support for this board? :)

**Comment by lyusupov** [comment] 2020-05-05 04:31
https://github.com/HelTecAutomation/platform-asrmicro

**Comment by lnlp** [comment] 2020-05-07 07:24
This is a duplicate of issue #11 and should therefore be closed.

@synth3 Check open issues first and do not post duplicates.

**Closed** 2020-05-07 12:20 UTC

**Comment by synth3** [comment] 2020-05-07 12:32
Thanks and sorry for not searching the issues properly! :)
